int      DoCompareTree (void);
int      DoCompareTreeParm (char *parmName, char *tkn);
int      DoSumt (void);
int      DoSumtParm (char *parmName, char *tkn);
int      DoTranslate (void);
int      DoTranslateParm (char *parmName, char *tkn);
int      DoTree (void);
int      DoTreeParm (char *parmName, char *tkn);
void     FlipBits (long int *partition, int length, long int *mask);
int      IsPartCompatible (long int *smaller, long int *larger, int length);
int      IsPartNested (long int *smaller, long int *larger, int length);
void     SortInts (int *item, int *assoc, int count, int descendingOrder);
void     SortInts2 (int *item, int *assoc, int left, int right, int descendingOrder);
