/*
 * Igrafu_UI.java
 *
 * Created on Jul 25, 2011, 11:13:54 PM
 */


package br.uesc.computacao.igrafu.apresentacao;


import br.uesc.computacao.igrafu.aplicacao.BuscarNexus;
import br.uesc.computacao.igrafu.aplicacao.InputSequence;
import br.uesc.computacao.util.ManipulaArquivo;
import java.awt.event.KeyEvent;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.SystemColor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;
import javax.swing.border.TitledBorder;


/**
 * Classe que desenha o gerenciador das opções do programa.
 * Inclui as escolhas de: Modo de Execução, Arquivo de Entrada, Metodos
 * e Programas.
 *
 * @author Anderson Carlos Sousa e Santos </br>
 * Orientadora: Martha Ximena Torres Delgado
 */
public class Igrafu_UI extends javax.swing.JFrame {

    /** Creates new form Igrafu_UI */
    public Igrafu_UI() {
        
        initComponents();
        this.setLocationRelativeTo(null); // Coloca a janela no centro da tela
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MedoDeExecucaoGroup = new ButtonGroup();
        MetodoDeReconstrucaoGroup = new ButtonGroup();
        jFileChooserSeq = new JFileChooser();
        jPanelModoDeExecucao = new JPanel();
        jPanelModoDeExeOpcoes = new JPanel();
        jRadioButtonOpManual = new JRadioButton();
        jRadioButtonOpPerfil = new JRadioButton();
        jRadioButtonOpAutomatico = new JRadioButton();
        jButtonModoDeExeAvancar = new JButton();
        ImagemDecorativa1 = new JLabel();
        jPanelFileIO = new JPanel();
        jTabbedPaneFileIO = new JTabbedPane();
        jPanelInput = new JPanel();
        jPanelFileInput = new JPanel();
        jTextFieldFileInput = new JTextField();
        jButtonFileInput = new JButton();
        jPanelFileFormat = new JPanel();
        jComboBoxFileFormat = new JComboBox();
        jPanelOptions = new JPanel();
        jPanelOutput = new JPanel();
        jPanelConversion = new JPanel();
        jButtonAvancarFile = new JButton();
        jButtonVoltarFile = new JButton();
        jPanelMetodos = new JPanel();
        jButtonMetodosAvancar = new JButton();
        imagemDecorativa2 = new JLabel();
        jPanelMetodosOpcoes = new JPanel();
        jRadioButtonOpMaxLikelihood = new JRadioButton();
        jRadioButtonOpDistance = new JRadioButton();
        jRadioButtonOpParcimonia = new JRadioButton();
        jRadioButtonOpBayes = new JRadioButton();
        jButtonMetodosVoltar = new JButton();
        jPanelProgramasBayes = new JPanel();
        jButtonProgramasBayesAvancar = new JButton();
        imagemDecorativa3 = new JLabel();
        jButtonProgramasBayesVoltar = new JButton();
        jPanelProgramasBayesOpcoes = new JPanel();
        jRadioButtonMrBayesOp = new JRadioButton();
        mrBayesUI1 = new MrBayesUI(this);
        jMenuBar = new JMenuBar();
        jMenuArquivo = new JMenu();
        jMenuItemExit = new JMenuItem();
        jMenuConfig = new JMenu();
        jMenulLanguage = new JMenu();
        jRadioButtonMenuItemEN = new JRadioButtonMenuItem();
        jRadioButtonMenuItemPT = new JRadioButtonMenuItem();
        jMenuProfile = new JMenu();
        jMenuItem2 = new JMenuItem();
        jMenuEdit = new JMenu();
        jMenuItemEditor = new JMenuItem();
        jMenuItemEditSeq = new JMenuItem();
        jMenuItemEditBatch = new JMenuItem();
        jMenuHelp = new JMenu();
        jMenuItem3 = new JMenuItem();
        FormListener formListener = new FormListener();

        jFileChooserSeq.setCurrentDirectory(new File("/home/acarlos/Codigos/Igrafu/Igrafu/Programs/mrbayes-3.1.2"));
        jFileChooserSeq.setDialogTitle("Sequencia ");

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("IGRAFU");
        setIconImage(new ImageIcon(getClass().getResource("/br/uesc/computacao/igrafu/apresentacao/resources/iconIGRAFU.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(new CardLayout());

        jPanelModoDeExecucao.setBackground(new Color(173, 200, 226));
        jPanelModoDeExecucao.addComponentListener(formListener);

        jPanelModoDeExeOpcoes.setBackground(new Color(173, 200, 226));
        jPanelModoDeExeOpcoes.setBorder(BorderFactory.createTitledBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(255, 255, 255)), "Modo de Execução:", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Dialog", 1, 12))); // NOI18N
        jPanelModoDeExeOpcoes.setOpaque(false);

        jRadioButtonOpManual.setBackground(new Color(173, 200, 226));
        MedoDeExecucaoGroup.add(jRadioButtonOpManual);
        jRadioButtonOpManual.setFont(new Font("DejaVu Sans", 1, 13));
        jRadioButtonOpManual.setSelected(true);
        jRadioButtonOpManual.setText("Manual");

        jRadioButtonOpPerfil.setBackground(new Color(173, 200, 226));
        MedoDeExecucaoGroup.add(jRadioButtonOpPerfil);
        jRadioButtonOpPerfil.setFont(new Font("DejaVu Sans", 1, 13));
        jRadioButtonOpPerfil.setText("Perfil");
        jRadioButtonOpPerfil.setEnabled(false);

        jRadioButtonOpAutomatico.setBackground(new Color(173, 200, 226));
        MedoDeExecucaoGroup.add(jRadioButtonOpAutomatico);
        jRadioButtonOpAutomatico.setFont(new Font("DejaVu Sans", 1, 13));
        jRadioButtonOpAutomatico.setText("Automatico");
        jRadioButtonOpAutomatico.setEnabled(false);

        GroupLayout jPanelModoDeExeOpcoesLayout = new GroupLayout(jPanelModoDeExeOpcoes);
        jPanelModoDeExeOpcoes.setLayout(jPanelModoDeExeOpcoesLayout);
        jPanelModoDeExeOpcoesLayout.setHorizontalGroup(
            jPanelModoDeExeOpcoesLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanelModoDeExeOpcoesLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanelModoDeExeOpcoesLayout.createParallelGroup(Alignment.LEADING)
                    .addComponent(jRadioButtonOpAutomatico)
                    .addComponent(jRadioButtonOpPerfil)
                    .addComponent(jRadioButtonOpManual))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanelModoDeExeOpcoesLayout.setVerticalGroup(
            jPanelModoDeExeOpcoesLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanelModoDeExeOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonOpManual)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonOpPerfil)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonOpAutomatico)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jButtonModoDeExeAvancar.setFont(new Font("DejaVu Sans", 1, 13));
        jButtonModoDeExeAvancar.setIcon(new ImageIcon(getClass().getResource("/br/uesc/computacao/igrafu/apresentacao/resources/avancar.png"))); // NOI18N
        jButtonModoDeExeAvancar.setText("Avançar");
        jButtonModoDeExeAvancar.addActionListener(formListener);


        ImagemDecorativa1.setIcon(new ImageIcon(getClass().getResource("/br/uesc/computacao/igrafu/apresentacao/resources/rna.png"))); // NOI18N
        GroupLayout jPanelModoDeExecucaoLayout = new GroupLayout(jPanelModoDeExecucao);
        jPanelModoDeExecucao.setLayout(jPanelModoDeExecucaoLayout);
        jPanelModoDeExecucaoLayout.setHorizontalGroup(
            jPanelModoDeExecucaoLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, jPanelModoDeExecucaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImagemDecorativa1, GroupLayout.PREFERRED_SIZE, 306, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanelModoDeExecucaoLayout.createParallelGroup(Alignment.LEADING)
                    .addGroup(Alignment.TRAILING, jPanelModoDeExecucaoLayout.createSequentialGroup()
                        .addComponent(jPanelModoDeExeOpcoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193))
                    .addGroup(Alignment.TRAILING, jPanelModoDeExecucaoLayout.createSequentialGroup()
                        .addComponent(jButtonModoDeExeAvancar, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        jPanelModoDeExecucaoLayout.setVerticalGroup(
            jPanelModoDeExecucaoLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanelModoDeExecucaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImagemDecorativa1, GroupLayout.PREFERRED_SIZE, 484, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelModoDeExecucaoLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jPanelModoDeExeOpcoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButtonModoDeExeAvancar, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        getContentPane().add(jPanelModoDeExecucao, "modoDeExecucao");

        jPanelFileIO.addComponentListener(formListener);

        jTabbedPaneFileIO.setBorder(BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTabbedPaneFileIO.setFont(new Font("DejaVu Sans", 1, 13));

        jPanelInput.setBackground(new Color(173, 200, 226));
        jPanelInput.setAutoscrolls(true);

        jPanelFileInput.setBorder(BorderFactory.createTitledBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(255, 255, 255)), "Arquivo da Sequência", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION, new Font("Dialog", 1, 12))); // NOI18N
        jPanelFileInput.setOpaque(false);
        jPanelFileInput.setRequestFocusEnabled(false);

        jTextFieldFileInput.setEditable(false);

        jButtonFileInput.setIcon(new ImageIcon(getClass().getResource("/br/uesc/computacao/igrafu/apresentacao/resources/folder_open.gif"))); // NOI18N
        jButtonFileInput.addActionListener(formListener);

        GroupLayout jPanelFileInputLayout = new GroupLayout(jPanelFileInput);
        jPanelFileInput.setLayout(jPanelFileInputLayout);
        jPanelFileInputLayout.setHorizontalGroup(
            jPanelFileInputLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, jPanelFileInputLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jTextFieldFileInput, GroupLayout.PREFERRED_SIZE, 262, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jButtonFileInput, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelFileInputLayout.setVerticalGroup(
            jPanelFileInputLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanelFileInputLayout.createSequentialGroup()
                .addGroup(jPanelFileInputLayout.createParallelGroup(Alignment.LEADING)
                    .addGroup(jPanelFileInputLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonFileInput, GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                    .addGroup(jPanelFileInputLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jTextFieldFileInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanelFileFormat.setBorder(BorderFactory.createTitledBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(255, 255, 255)), "Formato de Entrada", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION, new Font("Dialog", 1, 12))); // NOI18N
        jPanelFileFormat.setOpaque(false);

        jComboBoxFileFormat.setModel(new DefaultComboBoxModel(new String[] { "Nexus", "Selecione um Tipo...", "ACEDB", "Clustal", "EMBL", "Fasta", "GenBank", "MEGA", "MSF", "NBRF", " " }));
        jComboBoxFileFormat.setToolTipText("O formato de entrada do arquivo de sequencia. Nesta versão somente o formato \"nexus\" esta disponivel");
        jComboBoxFileFormat.setEnabled(false);

        GroupLayout jPanelFileFormatLayout = new GroupLayout(jPanelFileFormat);
        jPanelFileFormat.setLayout(jPanelFileFormatLayout);
        jPanelFileFormatLayout.setHorizontalGroup(
            jPanelFileFormatLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, jPanelFileFormatLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jComboBoxFileFormat, GroupLayout.PREFERRED_SIZE, 233, GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanelFileFormatLayout.setVerticalGroup(
            jPanelFileFormatLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanelFileFormatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxFileFormat, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        GroupLayout jPanelInputLayout = new GroupLayout(jPanelInput);
        jPanelInput.setLayout(jPanelInputLayout);
        jPanelInputLayout.setHorizontalGroup(
            jPanelInputLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, jPanelInputLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(jPanelInputLayout.createParallelGroup(Alignment.TRAILING, false)
                    .addComponent(jPanelFileFormat, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFileInput, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138))
        );
        jPanelInputLayout.setVerticalGroup(
            jPanelInputLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanelInputLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanelFileInput, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jPanelFileFormat, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPaneFileIO.addTab("Entrada", jPanelInput);

        jPanelOptions.setBackground(new Color(173, 200, 226));

        GroupLayout jPanelOptionsLayout = new GroupLayout(jPanelOptions);
        jPanelOptions.setLayout(jPanelOptionsLayout);
        jPanelOptionsLayout.setHorizontalGroup(
            jPanelOptionsLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );
        jPanelOptionsLayout.setVerticalGroup(
            jPanelOptionsLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        jTabbedPaneFileIO.addTab("Opções", jPanelOptions);

        jPanelOutput.setBackground(new Color(173, 200, 226));

        GroupLayout jPanelOutputLayout = new GroupLayout(jPanelOutput);
        jPanelOutput.setLayout(jPanelOutputLayout);
        jPanelOutputLayout.setHorizontalGroup(
            jPanelOutputLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );
        jPanelOutputLayout.setVerticalGroup(
            jPanelOutputLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        jTabbedPaneFileIO.addTab("Saida", jPanelOutput);

        jPanelConversion.setBackground(new Color(173, 200, 226));

        GroupLayout jPanelConversionLayout = new GroupLayout(jPanelConversion);
        jPanelConversion.setLayout(jPanelConversionLayout);
        jPanelConversionLayout.setHorizontalGroup(
            jPanelConversionLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );
        jPanelConversionLayout.setVerticalGroup(
            jPanelConversionLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        jTabbedPaneFileIO.addTab("Conversor", jPanelConversion);

        jButtonAvancarFile.setFont(new Font("DejaVu Sans", 1, 13));
        jButtonAvancarFile.setIcon(new ImageIcon(getClass().getResource("/br/uesc/computacao/igrafu/apresentacao/resources/avancar.png"))); // NOI18N
        jButtonAvancarFile.setMnemonic(KeyEvent.VK_ENTER);
        jButtonAvancarFile.setText("Avançar");
        jButtonAvancarFile.addActionListener(formListener);

        jButtonVoltarFile.setFont(new Font("DejaVu Sans", 1, 13));
        jButtonVoltarFile.setIcon(new ImageIcon(getClass().getResource("/br/uesc/computacao/igrafu/apresentacao/resources/voltar.png"))); // NOI18N
        jButtonVoltarFile.setText("Voltar");
        jButtonVoltarFile.setMaximumSize(new Dimension(99, 33));
        jButtonVoltarFile.setMinimumSize(new Dimension(99, 33));
        jButtonVoltarFile.setPreferredSize(new Dimension(99, 33));
        jButtonVoltarFile.addActionListener(formListener);

        GroupLayout jPanelFileIOLayout = new GroupLayout(jPanelFileIO);
        jPanelFileIO.setLayout(jPanelFileIOLayout);
        jPanelFileIOLayout.setHorizontalGroup(
            jPanelFileIOLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanelFileIOLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jTabbedPaneFileIO, GroupLayout.PREFERRED_SIZE, 640, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(jPanelFileIOLayout.createParallelGroup(Alignment.LEADING)
                    .addComponent(jButtonVoltarFile, GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(jButtonAvancarFile, GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelFileIOLayout.setVerticalGroup(
            jPanelFileIOLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanelFileIOLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelFileIOLayout.createParallelGroup(Alignment.TRAILING)
                    .addComponent(jTabbedPaneFileIO, GroupLayout.PREFERRED_SIZE, 434, GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFileIOLayout.createSequentialGroup()
                        .addComponent(jButtonAvancarFile, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addComponent(jButtonVoltarFile, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelFileIO, "fileIO");

        jPanelMetodos.setBackground(new Color(173, 200, 226));
        jPanelMetodos.addComponentListener(formListener);

        jButtonMetodosAvancar.setFont(new Font("DejaVu Sans", 1, 13));
        jButtonMetodosAvancar.setIcon(new ImageIcon(getClass().getResource("/br/uesc/computacao/igrafu/apresentacao/resources/avancar.png"))); // NOI18N
        jButtonMetodosAvancar.setText("Avançar");
        jButtonMetodosAvancar.addActionListener(formListener);


        imagemDecorativa2.setIcon(new ImageIcon(getClass().getResource("/br/uesc/computacao/igrafu/apresentacao/resources/rna.png"))); // NOI18N
        jPanelMetodosOpcoes.setBorder(BorderFactory.createTitledBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(255, 255, 255)), "Qual método deseja utilizar?", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION, new Font("Dialog", 1, 12))); // NOI18N
        jPanelMetodosOpcoes.setEnabled(false);
        jPanelMetodosOpcoes.setOpaque(false);

        jRadioButtonOpMaxLikelihood.setBackground(new Color(173, 200, 226));
        MetodoDeReconstrucaoGroup.add(jRadioButtonOpMaxLikelihood);
        jRadioButtonOpMaxLikelihood.setFont(new Font("DejaVu Sans", 1, 13));
        jRadioButtonOpMaxLikelihood.setText("Máxima Verosimilhança");
        jRadioButtonOpMaxLikelihood.setEnabled(false);

        jRadioButtonOpDistance.setBackground(new Color(173, 200, 226));
        MetodoDeReconstrucaoGroup.add(jRadioButtonOpDistance);
        jRadioButtonOpDistance.setFont(new Font("DejaVu Sans", 1, 13));
        jRadioButtonOpDistance.setText("Distância");
        jRadioButtonOpDistance.setEnabled(false);

        jRadioButtonOpParcimonia.setBackground(new Color(173, 200, 226));
        MetodoDeReconstrucaoGroup.add(jRadioButtonOpParcimonia);
        jRadioButtonOpParcimonia.setFont(new Font("DejaVu Sans", 1, 13));
        jRadioButtonOpParcimonia.setText("Parcimônia");
        jRadioButtonOpParcimonia.setEnabled(false);

        jRadioButtonOpBayes.setBackground(new Color(173, 200, 226));
        MetodoDeReconstrucaoGroup.add(jRadioButtonOpBayes);
        jRadioButtonOpBayes.setFont(new Font("DejaVu Sans", 1, 13));
        jRadioButtonOpBayes.setSelected(true);
        jRadioButtonOpBayes.setText("Bayes");

        GroupLayout jPanelMetodosOpcoesLayout = new GroupLayout(jPanelMetodosOpcoes);
        jPanelMetodosOpcoes.setLayout(jPanelMetodosOpcoesLayout);
        jPanelMetodosOpcoesLayout.setHorizontalGroup(
            jPanelMetodosOpcoesLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, jPanelMetodosOpcoesLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanelMetodosOpcoesLayout.createParallelGroup(Alignment.LEADING)
                    .addComponent(jRadioButtonOpMaxLikelihood, Alignment.TRAILING)
                    .addGroup(jPanelMetodosOpcoesLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanelMetodosOpcoesLayout.createParallelGroup(Alignment.LEADING)
                            .addComponent(jRadioButtonOpBayes)
                            .addGroup(jPanelMetodosOpcoesLayout.createParallelGroup(Alignment.TRAILING)
                                .addComponent(jRadioButtonOpParcimonia)
                                .addGroup(jPanelMetodosOpcoesLayout.createSequentialGroup()
                                    .addComponent(jRadioButtonOpDistance)
                                    .addGap(14, 14, 14))))
                        .addPreferredGap(ComponentPlacement.RELATED, 91, GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        jPanelMetodosOpcoesLayout.setVerticalGroup(
            jPanelMetodosOpcoesLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanelMetodosOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonOpMaxLikelihood)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonOpDistance)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonOpParcimonia)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonOpBayes)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jButtonMetodosVoltar.setFont(new Font("DejaVu Sans", 1, 13));
        jButtonMetodosVoltar.setIcon(new ImageIcon(getClass().getResource("/br/uesc/computacao/igrafu/apresentacao/resources/voltar.png"))); // NOI18N
        jButtonMetodosVoltar.setText("Voltar");
        jButtonMetodosVoltar.setMaximumSize(new Dimension(99, 33));
        jButtonMetodosVoltar.setMinimumSize(new Dimension(99, 33));
        jButtonMetodosVoltar.setPreferredSize(new Dimension(99, 33));
        jButtonMetodosVoltar.addActionListener(formListener);

        GroupLayout jPanelMetodosLayout = new GroupLayout(jPanelMetodos);
        jPanelMetodos.setLayout(jPanelMetodosLayout);
        jPanelMetodosLayout.setHorizontalGroup(
            jPanelMetodosLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, jPanelMetodosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagemDecorativa2, GroupLayout.PREFERRED_SIZE, 306, GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelMetodosLayout.createParallelGroup(Alignment.LEADING)
                    .addGroup(jPanelMetodosLayout.createSequentialGroup()
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(jPanelMetodosOpcoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMetodosLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addGroup(jPanelMetodosLayout.createParallelGroup(Alignment.TRAILING, false)
                            .addComponent(jButtonMetodosVoltar, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMetodosAvancar, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))))
                .addGap(64, 64, 64))
        );
        jPanelMetodosLayout.setVerticalGroup(
            jPanelMetodosLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanelMetodosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagemDecorativa2, GroupLayout.PREFERRED_SIZE, 484, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Alignment.TRAILING, jPanelMetodosLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanelMetodosOpcoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButtonMetodosAvancar, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jButtonMetodosVoltar, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanelMetodos, "metodos");

        jPanelProgramasBayes.setBackground(new Color(173, 200, 226));
        jPanelProgramasBayes.addComponentListener(formListener);

        jButtonProgramasBayesAvancar.setFont(new Font("DejaVu Sans", 1, 13));
        jButtonProgramasBayesAvancar.setIcon(new ImageIcon(getClass().getResource("/br/uesc/computacao/igrafu/apresentacao/resources/avancar.png"))); // NOI18N
        jButtonProgramasBayesAvancar.setText("Avançar");
        jButtonProgramasBayesAvancar.addActionListener(formListener);


        imagemDecorativa3.setIcon(new ImageIcon(getClass().getResource("/br/uesc/computacao/igrafu/apresentacao/resources/rna.png"))); // NOI18N
        jButtonProgramasBayesVoltar.setFont(new Font("DejaVu Sans", 1, 13));
        jButtonProgramasBayesVoltar.setIcon(new ImageIcon(getClass().getResource("/br/uesc/computacao/igrafu/apresentacao/resources/voltar.png"))); // NOI18N
        jButtonProgramasBayesVoltar.setText("Voltar");
        jButtonProgramasBayesVoltar.setMaximumSize(new Dimension(99, 33));
        jButtonProgramasBayesVoltar.setMinimumSize(new Dimension(99, 33));
        jButtonProgramasBayesVoltar.setPreferredSize(new Dimension(99, 33));
        jButtonProgramasBayesVoltar.addActionListener(formListener);

        jPanelProgramasBayesOpcoes.setBorder(BorderFactory.createTitledBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(255, 255, 255)), "Informe programa a ser utilizado", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION, new Font("Dialog", 1, 12))); // NOI18N
        jPanelProgramasBayesOpcoes.setEnabled(false);
        jPanelProgramasBayesOpcoes.setOpaque(false);

        jRadioButtonMrBayesOp.setBackground(new Color(173, 200, 226));
        jRadioButtonMrBayesOp.setFont(new Font("DejaVu Sans", 1, 13));
        jRadioButtonMrBayesOp.setSelected(true);
        jRadioButtonMrBayesOp.setText("MrBayes-3.1.2");

        GroupLayout jPanelProgramasBayesOpcoesLayout = new GroupLayout(jPanelProgramasBayesOpcoes);
        jPanelProgramasBayesOpcoes.setLayout(jPanelProgramasBayesOpcoesLayout);
        jPanelProgramasBayesOpcoesLayout.setHorizontalGroup(
            jPanelProgramasBayesOpcoesLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanelProgramasBayesOpcoesLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jRadioButtonMrBayesOp)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanelProgramasBayesOpcoesLayout.setVerticalGroup(
            jPanelProgramasBayesOpcoesLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanelProgramasBayesOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonMrBayesOp)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        GroupLayout jPanelProgramasBayesLayout = new GroupLayout(jPanelProgramasBayes);
        jPanelProgramasBayes.setLayout(jPanelProgramasBayesLayout);
        jPanelProgramasBayesLayout.setHorizontalGroup(
            jPanelProgramasBayesLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, jPanelProgramasBayesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagemDecorativa3, GroupLayout.PREFERRED_SIZE, 306, GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelProgramasBayesLayout.createParallelGroup(Alignment.LEADING)
                    .addGroup(jPanelProgramasBayesLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addGroup(jPanelProgramasBayesLayout.createParallelGroup(Alignment.TRAILING, false)
                            .addComponent(jButtonProgramasBayesVoltar, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonProgramasBayesAvancar, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                    .addGroup(jPanelProgramasBayesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanelProgramasBayesOpcoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64))
        );
        jPanelProgramasBayesLayout.setVerticalGroup(
            jPanelProgramasBayesLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanelProgramasBayesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagemDecorativa3, GroupLayout.PREFERRED_SIZE, 484, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Alignment.TRAILING, jPanelProgramasBayesLayout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(jPanelProgramasBayesOpcoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButtonProgramasBayesAvancar, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jButtonProgramasBayesVoltar, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanelProgramasBayes, "programasbayes");

        mrBayesUI1.addComponentListener(formListener);
        getContentPane().add(mrBayesUI1, "MrBayes");

        jMenuBar.setBackground(SystemColor.menu);

        jMenuArquivo.setText("Arquivo");

        jMenuItemExit.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0));
        jMenuItemExit.setMnemonic('X');
        jMenuItemExit.setText("Sair");
        jMenuItemExit.addActionListener(formListener);
        jMenuArquivo.add(jMenuItemExit);

        jMenuBar.add(jMenuArquivo);

        jMenuConfig.setText("Configuração");

        jMenulLanguage.setText("Idioma");

        jRadioButtonMenuItemEN.setText("Inglês");
        jMenulLanguage.add(jRadioButtonMenuItemEN);

        jRadioButtonMenuItemPT.setSelected(true);
        jRadioButtonMenuItemPT.setText("Português");
        jMenulLanguage.add(jRadioButtonMenuItemPT);

        jMenuConfig.add(jMenulLanguage);

        jMenuProfile.setText("Perfil");

        jMenuItem2.setText("Deletar Perfil");
        jMenuProfile.add(jMenuItem2);

        jMenuConfig.add(jMenuProfile);

        jMenuBar.add(jMenuConfig);

        jMenuEdit.setText("Editar");
        jMenuEdit.setToolTipText("");

        jMenuItemEditor.setText("Abrir editor de texto");
        jMenuEdit.add(jMenuItemEditor);

        jMenuItemEditSeq.setText("Editar sequência");
        jMenuItemEditSeq.setEnabled(false);
        jMenuEdit.add(jMenuItemEditSeq);

        jMenuItemEditBatch.setText("Editar Batch");
        jMenuItemEditBatch.setEnabled(false);
        jMenuEdit.add(jMenuItemEditBatch);

        jMenuBar.add(jMenuEdit);

        jMenuHelp.setText("Ajuda");

        jMenuItem3.setText("Sobre o IGRAFU");
        jMenuHelp.add(jMenuItem3);

        jMenuBar.add(jMenuHelp);

        setJMenuBar(jMenuBar);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements ActionListener, ComponentListener {
        FormListener() {}
        public void actionPerformed(ActionEvent evt) {
            if (evt.getSource() == jButtonModoDeExeAvancar) {
                Igrafu_UI.this.jButtonModoDeExeAvancarActionPerformed(evt);
            }
            else if (evt.getSource() == jButtonFileInput) {
                Igrafu_UI.this.jButtonFileInputActionPerformed(evt);
            }
            else if (evt.getSource() == jButtonAvancarFile) {
                Igrafu_UI.this.jButtonAvancarFileActionPerformed(evt);
            }
            else if (evt.getSource() == jButtonVoltarFile) {
                Igrafu_UI.this.jButtonVoltarFileActionPerformed(evt);
            }
            else if (evt.getSource() == jButtonMetodosAvancar) {
                Igrafu_UI.this.jButtonMetodosAvancarActionPerformed(evt);
            }
            else if (evt.getSource() == jButtonMetodosVoltar) {
                Igrafu_UI.this.jButtonMetodosVoltarActionPerformed(evt);
            }
            else if (evt.getSource() == jButtonProgramasBayesAvancar) {
                Igrafu_UI.this.jButtonProgramasBayesAvancarActionPerformed(evt);
            }
            else if (evt.getSource() == jButtonProgramasBayesVoltar) {
                Igrafu_UI.this.jButtonProgramasBayesVoltarActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemExit) {
                Igrafu_UI.this.jMenuItemExitActionPerformed(evt);
            }
        }

        public void componentHidden(ComponentEvent evt) {
        }

        public void componentMoved(ComponentEvent evt) {
        }

        public void componentResized(ComponentEvent evt) {
        }

        public void componentShown(ComponentEvent evt) {
            if (evt.getSource() == jPanelModoDeExecucao) {
                Igrafu_UI.this.jPanelModoDeExecucaoComponentShown(evt);
            }
            else if (evt.getSource() == jPanelFileIO) {
                Igrafu_UI.this.jPanelFileIOComponentShown(evt);
            }
            else if (evt.getSource() == jPanelMetodos) {
                Igrafu_UI.this.jPanelMetodosComponentShown(evt);
            }
            else if (evt.getSource() == jPanelProgramasBayes) {
                Igrafu_UI.this.jPanelProgramasBayesComponentShown(evt);
            }
            else if (evt.getSource() == mrBayesUI1) {
                Igrafu_UI.this.mrBayesUI1ComponentShown(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModoDeExeAvancarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonModoDeExeAvancarActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout)(getContentPane().getLayout());
        if(this.jRadioButtonOpManual.isSelected()){
            cl.show(getContentPane(), "fileIO");
        }
        if(this.jRadioButtonOpPerfil.isSelected()){
            //implementação futura
        }
        if(this.jRadioButtonOpAutomatico.isSelected()){
            //implementação futura
        }
}//GEN-LAST:event_jButtonModoDeExeAvancarActionPerformed

    private void jButtonMetodosAvancarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonMetodosAvancarActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout)(getContentPane().getLayout());
        if(this.jRadioButtonOpMaxLikelihood.isSelected()){
            //implementação futura
        }
        if(this.jRadioButtonOpDistance.isSelected()){
            //implementação futura
        }
        if(this.jRadioButtonOpParcimonia.isSelected()){
            //implementação futura
        }
        if(this.jRadioButtonOpBayes.isSelected()){
            cl.show(getContentPane(), "programasbayes");

        }

    }//GEN-LAST:event_jButtonMetodosAvancarActionPerformed

    private void jButtonMetodosVoltarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonMetodosVoltarActionPerformed
        voltar();
}//GEN-LAST:event_jButtonMetodosVoltarActionPerformed

    private void jButtonAvancarFileActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonAvancarFileActionPerformed
        String formato = this.jComboBoxFileFormat.getSelectedItem().toString();
        String file = this.jTextFieldFileInput.getText();
        
        if(this.jTextFieldFileInput.getText().equals("")){
            JOptionPane.showMessageDialog(this,
                                        "\nVocê não escolheu nenhum arquivo.\n\n "
                                        + "Para proseguir você deve inserir um\n "
                                        + "arquivo utilizando a caixa "
                                        + "\"Arquivo da Sequência\"\n  ",
                                        "Erro no arquivo de entrada",
                                        JOptionPane.WARNING_MESSAGE
                                        );
            return;
        }

        if(!ManipulaArquivo.existeArquivo(file)){
            JOptionPane.showMessageDialog(this,
                                        "\nVocê não escolheu um arquivo valido.\n\n "
                                        + "Este arquivo não existe.\n "
                                        + "Verifique se o arquivo não foi deletado\n\n",
                                        "Erro no arquivo de entrada",
                                        JOptionPane.WARNING_MESSAGE
                                        );
            return;
            
        }


        String datatype = BuscarNexus.defineDataType(file);
            
        if(datatype.equals("tipo_fail")){
            JOptionPane.showMessageDialog(this,
                                    "\nFoi identificado um tipo de dados invalido\n\n "
                                    + "Essa versão suporta somente\n "
                                    + "DNA ou proteina.\n",
                                    "Erro no arquivo de entrada",
                                    JOptionPane.WARNING_MESSAGE
                                    );
            return;
        }
        if(datatype.equals("no_datatype")){
            JOptionPane.showMessageDialog(this,
                                    "\nNão foi possivel identificar o tipo de dados.\n\n "
                                    + "Certifique-se que o arquivo selecionado contém\n "
                                    + "sequencias de dna ou proteina.\n\n",
                                    "Erro no arquivo de entrada",
                                    JOptionPane.WARNING_MESSAGE
                                    );
            return;
        }
        /*
         * Criação do arquivo de sequencia.
         */
        InputSequence inputSequence = new InputSequence(datatype, file, formato);


        java.awt.CardLayout cl = (java.awt.CardLayout)(getContentPane().getLayout());
        if(this.jRadioButtonOpManual.isSelected()){
            cl.show(getContentPane(), "metodos");
        }
        if(this.jRadioButtonOpPerfil.isSelected()){
            //implementação futura
        }
        if(this.jRadioButtonOpAutomatico.isSelected()){
            //implementação futura
        }
}//GEN-LAST:event_jButtonAvancarFileActionPerformed

    private void jButtonVoltarFileActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarFileActionPerformed
        voltar();
}//GEN-LAST:event_jButtonVoltarFileActionPerformed

    private void jButtonFileInputActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonFileInputActionPerformed
       int returnVal = jFileChooserSeq.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooserSeq.getSelectedFile();
              jTextFieldFileInput.setText( file.getAbsolutePath() );
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_jButtonFileInputActionPerformed

    private void jPanelFileIOComponentShown(ComponentEvent evt) {//GEN-FIRST:event_jPanelFileIOComponentShown
        this.jTabbedPaneFileIO.setEnabledAt(1, false);
        this.jTabbedPaneFileIO.setEnabledAt(2, false);
        this.jTabbedPaneFileIO.setEnabledAt(3, false);
        this.jTextFieldFileInput.requestFocus();
        this.setTitle("IGRAFU - Entrada");
    }//GEN-LAST:event_jPanelFileIOComponentShown

    private void jPanelMetodosComponentShown(ComponentEvent evt) {//GEN-FIRST:event_jPanelMetodosComponentShown
        this.jRadioButtonOpBayes.requestFocus();
        this.setTitle("IGRAFU - Métodos");
    }//GEN-LAST:event_jPanelMetodosComponentShown

    private void mrBayesUI1ComponentShown(ComponentEvent evt) {//GEN-FIRST:event_mrBayesUI1ComponentShown
        this.setTitle("IGRAFU - MrBayes");
    }//GEN-LAST:event_mrBayesUI1ComponentShown

    private void jButtonProgramasBayesAvancarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonProgramasBayesAvancarActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout)(getContentPane().getLayout());
        if(this.jRadioButtonMrBayesOp.isSelected()){
            cl.show(getContentPane(), "MrBayes");
        }
    }//GEN-LAST:event_jButtonProgramasBayesAvancarActionPerformed

    private void jButtonProgramasBayesVoltarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonProgramasBayesVoltarActionPerformed
        voltar();
    }//GEN-LAST:event_jButtonProgramasBayesVoltarActionPerformed

    private void jPanelProgramasBayesComponentShown(ComponentEvent evt) {//GEN-FIRST:event_jPanelProgramasBayesComponentShown
        this.jRadioButtonMrBayesOp.requestFocus();
        this.setTitle("IGRAFU - Programas");
    }//GEN-LAST:event_jPanelProgramasBayesComponentShown

    private void jMenuItemExitActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jPanelModoDeExecucaoComponentShown(ComponentEvent evt) {//GEN-FIRST:event_jPanelModoDeExecucaoComponentShown
        this.setTitle("IGRAFU - Modo de Execução");
    }//GEN-LAST:event_jPanelModoDeExecucaoComponentShown

    /**
     * Utiliza metodo do layout em carta (CardLayout) para exibir</br>
     * na janela o proximo component
     */
    public void avançar(){
        java.awt.CardLayout cl = (java.awt.CardLayout)(getContentPane().getLayout());
        cl.next(getContentPane());
        
    }

    /**
     * Utiliza metodo do layout em carta (CardLayout) para exibir</br>
     * na janela o componente anterior.
     */
    public void voltar(){
        java.awt.CardLayout cl = (java.awt.CardLayout)(getContentPane().getLayout());
        cl.previous(getContentPane());

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel ImagemDecorativa1;
    private ButtonGroup MedoDeExecucaoGroup;
    private ButtonGroup MetodoDeReconstrucaoGroup;
    private JLabel imagemDecorativa2;
    private JLabel imagemDecorativa3;
    private JButton jButtonAvancarFile;
    private JButton jButtonFileInput;
    private JButton jButtonMetodosAvancar;
    private JButton jButtonMetodosVoltar;
    private JButton jButtonModoDeExeAvancar;
    private JButton jButtonProgramasBayesAvancar;
    private JButton jButtonProgramasBayesVoltar;
    private JButton jButtonVoltarFile;
    private JComboBox jComboBoxFileFormat;
    private JFileChooser jFileChooserSeq;
    private JMenu jMenuArquivo;
    private JMenuBar jMenuBar;
    private JMenu jMenuConfig;
    private JMenu jMenuEdit;
    private JMenu jMenuHelp;
    private JMenuItem jMenuItem2;
    private JMenuItem jMenuItem3;
    private JMenuItem jMenuItemEditBatch;
    private JMenuItem jMenuItemEditSeq;
    private JMenuItem jMenuItemEditor;
    private JMenuItem jMenuItemExit;
    private JMenu jMenuProfile;
    private JMenu jMenulLanguage;
    private JPanel jPanelConversion;
    private JPanel jPanelFileFormat;
    private JPanel jPanelFileIO;
    private JPanel jPanelFileInput;
    private JPanel jPanelInput;
    private JPanel jPanelMetodos;
    private JPanel jPanelMetodosOpcoes;
    private JPanel jPanelModoDeExeOpcoes;
    private JPanel jPanelModoDeExecucao;
    private JPanel jPanelOptions;
    private JPanel jPanelOutput;
    private JPanel jPanelProgramasBayes;
    private JPanel jPanelProgramasBayesOpcoes;
    private JRadioButtonMenuItem jRadioButtonMenuItemEN;
    private JRadioButtonMenuItem jRadioButtonMenuItemPT;
    private JRadioButton jRadioButtonMrBayesOp;
    private JRadioButton jRadioButtonOpAutomatico;
    private JRadioButton jRadioButtonOpBayes;
    private JRadioButton jRadioButtonOpDistance;
    private JRadioButton jRadioButtonOpManual;
    private JRadioButton jRadioButtonOpMaxLikelihood;
    private JRadioButton jRadioButtonOpParcimonia;
    private JRadioButton jRadioButtonOpPerfil;
    private JTabbedPane jTabbedPaneFileIO;
    private JTextField jTextFieldFileInput;
    private MrBayesUI mrBayesUI1;
    // End of variables declaration//GEN-END:variables

}
